### ISSUE TITLE
Availability Zone and Region Name not exported with ElastiCache Clusters/ReservedNodes API 

### ISSUE THREAD

**Issue by posilva** [CloudHealth/cht_api_guide#101]
Hi, 
I am consuming the api in order to cross the inuse ElastiCache Cluster and the Reserved nodes:
- In the Web App we are able to see the region of the cluster or reserved node  but in the API these fields are not available
It would be interesting to have both AZ and Region in the clusters payload and Region and Engine in the Reserved Nodes

This way I can check how far are we from the Reservation compared with the InUse clusters
If there are any workaround (without having to go to AWS directly) please let me know

Thank you

Pedro

**Comment by HumanistSerif** [comment]
I have passed along this feedback to the Product Team. Thanks!
