### ISSUE TITLE
Drilldown Metrics for all resources

### ISSUE THREAD

**Issue by ElvenSpellmaker** [CloudHealth/cht_api_guide#107]
Is it possible to get the drill-down from the `azure_cost/history` API endpoint like it's possible from the website?

I'd like to get detailed information like the CSVs that can be downloaded from the website:
![image](https://user-images.githubusercontent.com/2286713/54302087-1e876700-45b8-11e9-95c3-36389cfc4ec3.png)

Thanks! =)

**Comment by HumanistSerif** [comment]
Hi @ElvenSpellmaker. Thanks for reaching out. CloudHealth does not provide an endpoint to get drill-down information for reports.

**Comment by RayWelker** [comment]
Is support for obtaining drilldown information a feature that could be added to CloudHealth?
