### ISSUE TITLE
Need integration for Grafana (plugin)

### ISSUE THREAD

**Issue by softwareklinic** [CloudHealth/cht_api_guide#30]
If you guys can write a plugin for Grafana/graphite would be awesome...

**Comment by utkarshcmu** [comment]
+1 to this

**Comment by dprofirovic** [comment]
+1

**Comment by jbrodley** [comment]
+1

**Comment by dpricha89** [comment]
+1

**Comment by donrudo** [comment]
+1

**Comment by HumanistSerif** [comment]
This feedback has been passed along to the Product team.

**Comment by halcyondude** [comment]
As there doesn’t seem to be a clean way to show CHT reports on a tv, would love to see an update here.  Please.

**Comment by guysoft** [comment]
@HumanistSerif Is there any documentation about the progress of this we can follow?

**Comment by guysoft** [comment]
Hey,
So filed a ticket on CloudHealth, along with our service provider, got this disappointing response:
The quote ``making any changes to the CloudHealth Platform`` suggests that its either a copy-paste response, or that the Technical Support Engineer at CloudHealth does not understand that the point of the API is that you don't need to modify the CloudHealth Platform to enable this functionality.

```
Hi Guy,

Thank you for your feedback about the CloudHealth Platform! While we cannot commit to making any changes to the CloudHealth Platform, this feedback will be submitted to the Product Management team so that it can be reviewed as part of their roadmap planning.

I’ll mark this ticket as solved as no further response or action is required on your end.

Thanks,


Alex Blayer
Technical Support Engineer
CloudHealth Technologies, Inc.
ablayer@cloudhealthtech.com
```

**Comment by halcyondude** [comment]
bump.  I'm an active CHT customer.  I'm thrilled that CHT is using github to track issues.

Having a response to this other than merely closing it would be helpful.

https://grafana.com/grafana/dashboards/139

Please advise and thanks.

**Comment by guysoft** [comment]
@halcyondude File some internal request. They don't answer.

Also, meanwhile I wrote a slack bot that posts every day our total from two days back, using CHT's API (which is really a total mess for anything other than their dashboard, would explain why they are so unwilling to corporate, but not their rudeness).
