### ISSUE TITLE
No support for MSP

### ISSUE THREAD

**Issue by elmobp** [CloudHealth/cht_api_guide#39]
There is no API support for MSP accounts, this becomes a right mess when we need to do things in the parent and child accounts. Is there a plan to expose an API for MSP?

**Comment by vpillai** [comment]
Michael, Can you please be more specific about the changes you need to make as an MSP? Our objective is to enable APIs to effect all changes that can be done in the UI. If we can understand your objective and use-case better, it would help us define what needs to be added. 

Thanks!

**Comment by elmobp** [comment]
Sure, had a call with Chris about this and a support ticket!

We need a way to manipulate all the MSP data to make adjustments, at the moment as it stands we can extract the "MSP accounts" but trying to work with the "AWS accounts" inside of them is not possible, we can see the accounts but the API is not feeding the id back that is needed to make adjustments to the account.

To be simple we need to adjust a feature on every account but the CHT ID does not come back on the MSP API query the AWS accounts on a MSP you will see what I mean case #6851

**Comment by vpillai** [comment]
I took a quick look at case #6851. As I understood it there were a couple
of issues:

> Given that when we add accounts as a partner it creates new aws accounts
so duplicates (Bug??)..
We only create a new account by copying from partner if one doesn't already
exist in the customer. No "duplicate" should be created.

>  I have done this at the level root but if I switch to a customer the
external id has not been copied across.
The external-id part of the credential should be mapped correctly if
CloudHealth made the copy.

There seems to be some other question of being able to update the customer
accounts with an API key at the partner level.
Are you running into an issue doing that?

Thanks,
Vikram


*Vikram Pillai*

Chief Architect, Founding Engineer

280, Summer Street

Boston, MA 02210

C: 978.853.6803


<https://www.cloudhealthtech.com>

<https://www.facebook.com/CloudHealthTech>
<https://twitter.com/CloudHealthTech>
<https://plus.google.com/+Cloudhealthtech>
<https://www.linkedin.com/company/2838309?trk=tyah&trkInfo=clickedVertical%3Acompany%2CclickedEntityId%3A2838309%2Cidx%3A2-2-3%2CtarId%3A1479399288038%2Ctas%3Acloudh>
<https://www.youtube.com/channel/UCR3YerNN67OyIq5mnla5s1w>
<https://www.cloudhealthtech.com>

**Comment by elmobp** [comment]
Hey Vikram,

Yeh, maybe its easier to get on a call / webex to show you what’s happening? I am trying to update AWS accounts at a partner level, I can get a list of the client accounts with there customer id’s, then when I search the API via https://chapi.cloudhealthtech.com/api/search.json?api_version=2&api_key=<api_key>&client_api_id=<client_api_id>&name=AwsAccount<https://chapi.cloudhealthtech.com/api/search.json?api_version=2&api_key=%3Capi_key%3E&client_api_id=%3Cclient_api_id%3E&name=AwsAccount> I would expect to see an id coming back in that response. There is no id coming back which makes it not possiblt to issue an update to the external id for the child accounts.

Cheers!

--
Michael Baker
Product Engineering Specialist | Bulletproof - Mission Critical Cloud

e: michael.baker@bulletproof.net<mailto:michael.baker@bulletproof.net>
w: www.bulletproof.net.au<http://www.bulletproof.net.au/>
m: +61 430 069 855
Connect: twitter @bulletproofnet | LinkedIn

Bulletproof Group Ltd (ASX:BPF)
Amazon Web Services (AWS) Premier Partner

**Comment by vpillai** [comment]
Mike, 

I reviewed this issue with Chris and the engineer.
We have isolated the primary issue that is blocking you and Chris has communicated a solution for you. Hopefully this works for you.

I do not quite understand all the challenges that you describe above, so if you still cannot achieve your objective, I'm happy to jump on a short call tomorrow. I'm in Las Vegas for re:Invent so I'm in GMT-08:00 TZ. I'm open in morning 10am - 1pm.

/v

**Comment by elmobp** [comment]
Hey Vikram,

That “fix” did not work either ☹ hmm this could be fun im +8

--
Michael Baker
Product Engineering Specialist| Bulletproof - Mission Critical Cloud

e: michael.baker@bulletproof.net<mailto:michael.baker@bulletproof.net>
w: www.bulletproof.net.au<http://www.bulletproof.net.au/>
m: +61 430 069 855
Connect: twitter @bulletproofnet | LinkedIn

Bulletproof Group Ltd (ASX:BPF)
Amazon Web Services (AWS) Premier Partner

**Comment by vpillai** [comment]
Hi Mike, Do you have a few minutes now? It's 23:43 here, so +8 +8 = 15:43.
By the time I wake up in 6 hours, might be too late for you.
I can send you a google hangout by email @ michael.baker@bulletproof.net

**Comment by elmobp** [comment]
Yep go for it

--
Michael Baker
Product Engineering Specialist| Bulletproof - Mission Critical Cloud

e: michael.baker@bulletproof.net<mailto:michael.baker@bulletproof.net>
w: www.bulletproof.net.au<http://www.bulletproof.net.au/>
m: +61 430 069 855
Connect: twitter @bulletproofnet | LinkedIn

Bulletproof Group Ltd (ASX:BPF)
Amazon Web Services (AWS) Premier Partner

**Comment by elmobp** [comment]
Im +8 but I work +11 just to make things more fun for us all!

--
Michael Baker
Product Engineering Specialist| Bulletproof - Mission Critical Cloud

e: michael.baker@bulletproof.net<mailto:michael.baker@bulletproof.net>
w: www.bulletproof.net.au<http://www.bulletproof.net.au/>
m: +61 430 069 855
Connect: twitter @bulletproofnet | LinkedIn

Bulletproof Group Ltd (ASX:BPF)
Amazon Web Services (AWS) Premier Partner

**Comment by HumanistSerif** [comment]
Hi @elmobp. Is it okay to close out this issue at this point?
