### ISSUE TITLE
Is there any support for retrieving rendered graphics from CloudHealth?

### ISSUE THREAD

**Issue by oldnerd** [CloudHealth/cht_api_guide#41]
Do you offer or plan to offer an API that retrieves graphics/charts from cloudhealth, or is the plan to just output the data sets and allow the consumer to do so?

**Comment by vpillai** [comment]
You can retrieve the chart graphics on the console or subscribe to an interactive report and the chart will be delivered via email. May we understand your use case for automating the retrieval of the chart via an API?

Thanks!
/v
