### ISSUE TITLE
CloudHealth Query Language

### ISSUE THREAD

**Issue by kyrogue** [CloudHealth/cht_api_guide#45]
Hello, where can the documentation for writing the query language be found?

**Comment by HumanistSerif** [comment]
@kyrogue Are you looking for documentation different from what is available at https://apidocs.cloudhealthtech.com?

**Comment by KamranKhan-Dev** [comment]
@HumanistSerif it would be great if there were more examples documented there and also expanded a bit on how to use operators.  Currently only `=` is documented as an operator via the examples.  How would I perform a `contains` operation.  This is particularly required when searching by tag name and value.
