### ISSUE TITLE
Base API endpoint is unavailable

### ISSUE THREAD

**Issue by YaroslavaR** [CloudHealth/cht_api_guide#48]
Hi!

The base API endpoint - https://chapi.cloudhealthtech.com/ - seems to be unavailable.
We receive a 503 when we try to run our reporting code or try to access the page from the browser.

Is there any ETA on when the service is going to be up again? Or has the URL changed perhaps?

Thanks!
Yasia

**Comment by HumanistSerif** [comment]
Please reach out to support@cloudhealthtech.com if you experience endpoint unavailability.
