### ISSUE TITLE
Recommendations API?

### ISSUE THREAD

**Issue by oldnerd** [CloudHealth/cht_api_guide#50]
Is there support for retrieving data from the recommendations section of the CH web site?  Specifically, the EC2 instance rightsizing recommendations?

Thanks.

**Comment by oldnerd** [comment]
The URL pattern in the UI would lead one to expect it to be available under the metrics reporting tree - but it's not in the index.

**Comment by melusom** [comment]
+1 
The API documentation specifies that currently only single-asset metrics can be returned via the metrics API at this time.

**Comment by beireia** [comment]
+1
To get around this we're setting up a process to manually grab the report that's emailed to us and shove that elsewhere. It's quite gross.

**Comment by HumanistSerif** [comment]
Closing this issue, because a Recommendations API is currently unavailable.
