### ISSUE TITLE
assume_role_external_id should not be required when creating accounts

### ISSUE THREAD

**Issue by elmobp** [CloudHealth/cht_api_guide#54]
On both account and partner API you require us to pass in an external id when creating accounts. There is no way via the API to get an external id. This means we would need to either a) screen scrape or b) reuse an existing which defeats the whole security model for wanting this in the first place.

I think the external id param should be optional to be flexible for those who want to use the same external id on multiple accounts. If one is not specified it should create it and return it via the API call to create the account

**Comment by HumanistSerif** [comment]
Closing old issues. Please feel free to reopen.
