### ISSUE TITLE
Search in the docs doesn't seem to work beyond the title of a page.   

### ISSUE THREAD

**Issue by SteveTalt** [CloudHealth/cht_api_guide#69]
Not sure if that was the intent or not, but it makes real hard to use the docs to search for pertinent examples.   for example:   search for page or api_version.    Both in the docs....both return zero results.     Workaround is to search the repo, but doesn't seem to be the intent here if you are publishing these docs with a search bar.

**Comment by HumanistSerif** [comment]
@SteveTalt Thanks for the feedback. I pushed out a change to the search index in https://github.com/CloudHealth/cht_api_guide/pull/70. Let me know how the search is working for you.
