### ISSUE TITLE
Typo in customer statement endpoint URL

### ISSUE THREAD

**Issue by jfreeland** [CloudHealth/cht_api_guide#82]
https://raw.githubusercontent.com/CloudHealth/cht_api_guide/master/_partner/cust-statement-read-single.md :
endpoint: https://chapi.cloudhealthtech.com/customer_statements/:id

https://raw.githubusercontent.com/CloudHealth/cht_api_guide/master/_partner/cust-statement-read-multiple.md :
endpoint: https://chapi.cloudhealthtech.com/customer_statements/:id

You're missing the /v1/ in the URL.

**Comment by HumanistSerif** [comment]
Thanks for the feedback, @jfreeland. I have fixed this error in #84.
